# Generated by Django 2.1.7 on 2019-03-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlanddata',
            name='size_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
