# Generated by Django 2.1.7 on 2019-03-23 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0002_rawlanddata_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawlanddata',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='date_collected',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='heading',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='land_availability',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='land_size',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='land_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='location1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='location2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='price_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawlanddata',
            name='size_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
