# Generated by Django 2.1.7 on 2019-03-28 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0003_auto_20190323_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHouseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, null=True)),
                ('location1', models.CharField(max_length=30, null=True)),
                ('location2', models.CharField(max_length=30, null=True)),
                ('bedrooms', models.IntegerField(default=0, null=True)),
                ('bathrooms', models.IntegerField(default=0, null=True)),
                ('floor_area', models.IntegerField(default=0, null=True)),
                ('floors', models.IntegerField(default=1, null=True)),
                ('parking', models.IntegerField(default=0, null=True)),
                ('property_type', models.CharField(max_length=20, null=True)),
                ('land_size', models.FloatField(default=0, null=True)),
                ('land_availability', models.CharField(max_length=20, null=True)),
                ('heading', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
