# Generated by Django 2.1.7 on 2019-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0004_rawhousedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawhousedata',
            name='bathrooms',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='rawhousedata',
            name='bedrooms',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
