# Generated by Django 2.1.7 on 2019-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0002_tempproclanddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclanddata',
            name='aesthetic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='beach',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='coconut',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='cultivated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='highway',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='paddy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='quarry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='rubber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='school',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='supermarket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='tea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proclanddata',
            name='utilities',
            field=models.IntegerField(default=0),
        ),
    ]
