# Generated by Django 2.1.7 on 2019-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0005_proclanddata_days_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcHouseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('bedrooms', models.IntegerField(default=1, null=True)),
                ('bathrooms', models.IntegerField(default=1, null=True)),
                ('floor_area', models.FloatField(default=0, null=True)),
                ('floors', models.IntegerField(default=1, null=True)),
                ('parking', models.IntegerField(default=0, null=True)),
                ('land_size', models.FloatField(default=0, null=True)),
                ('land_availability', models.CharField(max_length=20, null=True)),
                ('water', models.IntegerField(default=0, null=True)),
                ('overhead', models.IntegerField(default=0, null=True)),
                ('garage', models.IntegerField(default=0, null=True)),
                ('p_garden', models.IntegerField(default=0, null=True)),
                ('servant', models.IntegerField(default=0, null=True)),
                ('hot_water', models.IntegerField(default=0, null=True)),
                ('electricity', models.IntegerField(default=0, null=True)),
                ('ac_rooms', models.IntegerField(default=0, null=True)),
                ('luxury', models.IntegerField(default=0, null=True)),
                ('brand_new', models.IntegerField(default=0, null=True)),
                ('security', models.IntegerField(default=0, null=True)),
                ('roof_garden', models.IntegerField(default=0, null=True)),
                ('in_garden', models.IntegerField(default=0, null=True)),
                ('furnished', models.IntegerField(default=0, null=True)),
                ('pool', models.IntegerField(default=0, null=True)),
                ('colonial', models.IntegerField(default=0, null=True)),
                ('front', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
