# Generated by Django 2.1.7 on 2019-03-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0005_auto_20190329_1257'),
        ('dataprocess', '0006_prochousedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prochousedata',
            name='raw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webscrape.RawHouseData'),
        ),
    ]
