# Generated by Django 2.1.7 on 2019-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0008_prochousedata_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='prochousedata',
            name='km',
            field=models.IntegerField(null=True),
        ),
    ]
