# Generated by Django 2.1.7 on 2019-04-05 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0011_auto_20190405_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogentries',
            name='date_searched',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 16, 32, 59, 232116)),
        ),
    ]
