# Generated by Django 2.1.7 on 2019-04-05 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0012_auto_20190405_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='housebacklog',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='landbacklog',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='backlogentries',
            name='date_searched',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 17, 51, 22, 54024)),
        ),
    ]
