# Generated by Django 2.1.7 on 2019-04-05 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0013_auto_20190405_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogentries',
            name='date_searched',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 17, 58, 16, 996296)),
        ),
        migrations.AlterField(
            model_name='backlogentries',
            name='search_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
