# Generated by Django 2.1.7 on 2019-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0014_auto_20190405_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogentries',
            name='date_searched',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
