# Generated by Django 2.1.7 on 2019-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0015_auto_20190405_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogentries',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
